### DISCUSSION TITLE
Config file keeps getting overwritten

### DISCUSSION THREAD

**Discussion by twist3dimages** [cross-seed/cross-seed#394] [Q&A]
Not sure why it keeps doing this but I'm running it in a docker container. I've tried to set the /config directory to read only but every time I save settings, it doesn't apply when I open the file again. Tried multiple directories without any luck

OS: Unraid

**Comment by mmgoodnow** [comment]
config dir needs R/W. Can you show your docker configuration

**Reply by Romain-Donze** [reply]
It would be nice to have a follow up to this issue. I have the same problem where my config.js file get overwritten when starting my docker stack

Here is my docker-compose file

```
version: "3.8"

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    hostname: gluetun
    cap_add:
      - NET_ADMIN
    networks:
      - downloadarr
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_PORT_FORWARDING=on
      - VPN_PORT_FORWARDING_PROVIDER=protonvpn
      - WIREGUARD_PRIVATE_KEY=xxx
      - WIREGUARD_PUBLIC_KEY=xxx
      - WIREGUARD_ADDRESSES=xxx
      - WIREGUARD_ENDPOINT_IP=xxx
      - WIREGUARD_ENDPOINT_PORT=xxx
      - DNS=1.1.1.1,1.0.0.1
      - FIREWALL=on
    ports:
      - 9080:9080 
    restart: unless-stopped
    
  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: service:gluetun
    depends_on:
      - gluetun
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Zurich
      - WEBUI_PORT=9080
      - WEBUI_HOST=0.0.0.0
    volumes:
      - /volume2/docker/downloadarr/qbittorrent:/config
      - /volume1/Medias:/data
    restart: unless-stopped
    
  flaresolverr: 
    image: ghcr.io/flaresolverr/flaresolverr:latest 
    container_name: flaresolverr 
    hostname: flaresolverr 
    networks: 
      - downloadarr 
    environment: 
      - LOG_LEVEL=${LOG_LEVEL:-info} 
      - LOG_HTML=${LOG_HTML:-false} 
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none} 
      - TZ=Europe/Zurich
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    hostname: prowlarr 
    networks: 
      - downloadarr 
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Zurich
    volumes:
      - /volume2/docker/downloadarr/prowlarr:/config
    ports:
      - 9081:9696
    restart: unless-stopped
    depends_on: 
      - flaresolverr 

  cross-seed:
    image: ghcr.io/cross-seed/cross-seed:latest
    container_name: cross-seed
    network_mode: service:gluetun
    user: 1026:100
    ports:
      - 2468:2468
    depends_on:
      - qbittorrent 
      - prowlarr 
    environment:
      - TZ=Europe/Zurich
    volumes:
      - /volume2/docker/downloadarr/cross-seed:/config
      - /volume1/Medias:/data:ro
    restart: unless-stopped
    
networks:
  downloadarr: 
    driver: bridge
```
