### DISCUSSION TITLE
[Issue + Workaround] Invalid TorrentDir after upgrade to v6.6

### DISCUSSION THREAD

**Discussion by GeoffreyCoulaud** [cross-seed/cross-seed#859] [General]
## Context

I'm using qbittorrent and cross-seed in docker, both having their own docker volume for persistent data.  
After an update to my cross-seed container to v6.6 it wouldn't start and instead throw an error:

`error: Invalid torrentDir, if no torrents are in client set to null for now`

## Why the problem happens

This is caused by commit [7821bec3a3105553a5f028788566b67866aa136e](https://github.com/cross-seed/cross-seed/commit/7821bec3a3105553a5f028788566b67866aa136e) which introduces a check for the presence of `.fastresume` files.  

What I naively did was point cross-seed to a directory where .torrent files are copied to (set in qbittorrent) and it worked like a charm. This dir doesn't contain fast resume data however, and should not be used with cross-seed, that's my mistake.

## Workaround

I now mount my qbittorrent docker volume in the cross-seed container (read only) to `/qbt-config`.
Additionnaly, in the cross-seed config, I set `torrentDir: "/qbt-config/data/BT_backup"`.

Hope this helps someone :)

**Comment by zakkarry** [comment]
If you followed the documentation you'd see that the BT_backup folser is given as the directory to use, and not the copy to directories.

https://www.cross-seed.org/docs/basics/faq-troubleshooting#what-is-could-not-ensure-all-torrents-from-the-torrent-client-are-in-torrentdir

Full details here

We don't really support running it with "Copy Of .torrent" directories, and that's why we give the explanation and examples we do, so its not really an issue as much as emphasizing an easy error.

**Reply by GeoffreyCoulaud** [reply]
I admit that I didn't read that part of the troubleshooting wiki haha, but again that's my mistake.

I think it may be valuable to repeat the warning found there in the torrentDir options docs.

**Reply by zakkarry** [reply]
It's mentioned and linked there now too, however, there is an entire chart there already with paths for each client's torrent file store.

**Reply by GeoffreyCoulaud** [reply]
Great, thanks :)

To be clear, I know it's not supported and I made a mistake. I just pointed it here because I thought other people may have the same problem.

**Reply by zakkarry** [reply]
Yea, I appreciate that - don't get my insistence and repetitious stating that it isn't and that the docs cover this now (and I added the section to the options->torrentDir page due to your pointing out its absence - thanks) as dismissing your validity.

We've seen users do this before, and despite the chart and other places in the documentation, we do sometimes miss putting it in obvious places, so your pointing this out is appreciated. Our experience with the documentation as developers writing it is not always congruent with a new user (or any user) experience.

The issue really is that when we say "your client's torrent store/config directory, etc" it is not always known by a user - particularly one new to this type of application and its interactions, that this directory even exists. 

Thanks for helping us improve the coverage of this issue, if you know of any other places this could be included to emphasize it more, please feel free to let us know.

**Reply by GeoffreyCoulaud** [reply]
I can see some possible improvements: 

---

The docker warning under the `torrentDir` option may not be applicable, and that may confuse users.
 
> Docker
> Leave the torrentDir as /torrents and use Docker to map your directory to /torrents.

In some situations, the advice doesn't apply since it's not possible to mount directly a subpath of a docker volume:

<details>
<summary>compose.yml</summary>

```yml
volumes:
  cross-seed-config:
  qbittorrent-config:

services:

  qbittorrent:
    image: ghcr.io/hotio/qbittorrent:release-5.0.1
    environment:
      WEBUI_PORTS: 80/tcp,80/udp
    volumes:
      - qbittorrent-config:/config
      - ./qbittorrent/data:/data

  cross-seed:
    image: ghcr.io/cross-seed/cross-seed
    command: daemon
    environment:
      CONFIG_DIR: /config
      QBITTORRENT_URL: http://qbittorrent
    volumes:
      - cross-seed-config:/config
      - ./cross-seed/seeds:/cross-seeds
      # Needed to access the torrent files and fast resume data
      - qbittorrent-config:/qbt-config:ro
    depends_on:
      - qbittorrent
```

</details>

In `config.js`, the torrentDir will then be `"/qbt-config/data/BT_backup"`.

---

The wording for the config option section suggests that the table is a suggestion, whereas it is in fact the expected behaviour.

> Point this at a directory containing torrent files. If you don't know where your torrent client stores its files, the table below might help.

In my opinion, this would be better:

> Point this at the directory containing the torrent files *currently visible* in the torrent client. 
> Please refer to the table below for the right directory depending on your torrent client.

--- 

Other than those, it seems good to me!
