### ISSUE TITLE
Feature Request: qBittorrent Hardlink Categories

### ISSUE THREAD

**Issue by undaunt** [cross-seed/cross-seed#213]
Hello,

**Use Case 1**
File A is downloaded into a qBittorrent category called "Downloads - ISO" which, with qBittorrent automatic management, points to `/downloads/complete/iso/`. Currently, the way I understand injection with daemon mode to work, the cross-seeding torrent from another tracker would also be inserted (with default tag cross-seed) into the same category and folder location. This category, or a generic Radarr or Sonarr category, may only be a placeholder category for new incoming files and not match my category organization for longer term storage.

If I move one of the copies of the torrent in the interface, the second copy is now pointing to missing data and I need to manually move that torrent's category as well. This inhibits my ability to leverage qBittorrent's automatic torrent management mode to manipulate where data lives on the server.

**Use Case 2**
Preexisting torrents that are scanned using scan mode instead of daemon mode will do the same behavior as use case 1. If I am storing files in a per tracker subfolder system, eg: `/downloads/seed/BHD` and I'm trying to cross seed to NBL in `/downloads/seed/NBL` right now both torrents will appear, seeding, in the BHD category and folder location. I'm then left with the use case 1 dilemma of missing data due to automatic management.

**Use Case 3**
Torrents are matched in daemon mode immediately upon completion. For users who have 1 category for Sonarr downloads (or similar) and a subsequent category for imported Sonarr downloads, if the cross-seeded torrents are injected into the first category, they may cause additional looping imports. Eg: A season of a show could be imported after cross-seed injection, thus it is imported, overwritten and imported by cross-seed 1, then imported and overwritten again by cross-seed 2.

In either case, a manual action must be taken to move one of the torrent's categories, hardlink the content of the torrent, then re-scan the data in the secondary category. It would be ideal to be able to pass through a custom qBittorrent category (or even better, a category per Prowlarr tracker optionally) that would auto hardlink the data instead of leaving it in place with the original data. 

This would be an optional flag as not all users require hardlinks.

What are your thoughts on this? Thanks very much!

**Comment by mmgoodnow** [comment]
Thanks for the very detailed write up! 

Hard links, symlinks, and partial data are an area of complexity that, when I wrote cross-seed initially, I struck a hard line stance against. That said, cross-seed has become a bit popular, and I will consider anything if enough people want it.

This feature proposal involves not only complexity in matching, but also complexity of configuration, which is made even more complicated by the fact that it would only work with qBittorrent. Please propose what the configuration would look like, both in the config.js format, and in CLI format (the hard one).

**Comment by undaunt** [comment]
Here is my first take on the CLI format. I'll circle around on the config.js format as soon as I can. Work has been extremely busy. If you have any thoughts on this though, I can update/amend before taking a crack at config.js. I've tried to add extra detail to each command flag to suggest possible functionality, defaults, etc.

Using my config as an example, here is my current compose state:

```
  qb-tv:
    image: lscr.io/linuxserver/qbittorrent:14.3.9
    container_name: qb-tv
    restart: unless-stopped
    network_mode: service:wireguard
    security_opt:
      - no-new-privileges:true
    depends_on:
      - wireguard
    volumes:
      - $DOCKERDIR/qb-tv:/config
      - $DLDIR:/downloads
    environment:
      - TZ
      - PUID
      - PGID
      - WEBUI_PORT=$WG_QB_PORT2 # Listening port 58477

  cs-tv:
    image: mmgoodnow/cross-seed
    container_name: cs-tv
    restart: unless-stopped
    networks:
      - $TRAEFIK_NETWORK
    security_opt:
      - no-new-privileges:true
    user: $PUID:$PGID
    #ports:
    #  - $CS_TV_PORT:2468
    volumes:
      - $DOCKERDIR/cross-seed-tv:/config
      - $DLDIR/torrents/tv:/torrents:ro
      - $DLDIR/watched/tv:/output
    #command: search -i /torrents -s /output -e -a -A inject --qbittorrent-url http://wireguard:$WG_QB_PORT2 -T http://prowlarr:$PROWLARR_PORT/25/api?apikey=$TRACKER1_KEY http://prowlarr:$PROWLARR_PORT/20/api?apikey=$TRACKER2_KEY http://prowlarr:$PROWLARR_PORT/19/api?apikey=$TRACKER3_KEY http://prowlarr:$PROWLARR_PORT/24/api?apikey=$TRACKER4_KEY
    command: daemon -i /torrents -s /output -e -a -A inject --qbittorrent-url http://wireguard:$WG_QB_PORT2 -T http://prowlarr:$PROWLARR_PORT/25/api?apikey=$TRACKER1_KEY http://prowlarr:$PROWLARR_PORT/20/api?apikey=$TRACKER2_KEY http://prowlarr:$PROWLARR_PORT/19/api?apikey=$TRACKER3_KEY http://prowlarr:$PROWLARR_PORT/24/api?apikey=$TRACKER4_KEY
```

I have the daemon command for regular usage of the container, however on first run prior to using the daemon I'd do a 1 time load of existing .torrent files using the search command. In either case, the subsequent flags would be the same. I'm anticipating any future hard/soft link flags, category flags, etc. would also mirror across commands for my use case.

Let's assume I'm grabbing most of my TV files from tracker 1, but in case I sometimes grab one from tracker 2 or 3, I want to compare all snatched files against all trackers for maximum cross-seeding. Perhaps we could define something like this:

```
-ln   Enables hardlinks for detected cross-seed torrents during injection. (Requires a directory or per-torznab directory linkdir via -ld or -ldn. Default: false. If enabled with -A of "save", does nothing.)
-lns   Enables symlinks for detected cross-seed torrents during injection. (Requires a directory or per-torznab directory linkdir via -ld or -ldn. Default: false. If enabled with -A of "save", does nothing.)

-ld, --linkdir    Specifies the folder path within qBittorrent that all cross-seeded torrents should be linked into for all trackers. (Fallback for blank Torznab specific folders. Requires hard or symlinks. If -ln/-lns not specified in conjunction with -ld, defaults to -ln. Default: false)
```

Using the above logic, I could improve current workflows by at least keeping all cross-seed torrents in a separate location, allowing me to still move data between various other qB categories via Automatic Torrent Management (or manually, I guess). Perhaps I intake net new files for Sonarr to `/downloads/complete/tv/`, then move them to `/downloads/seed/tracker1/` or `/downloads/seed/tracker2/` after the fact. By keeping the cross-seeded torrents separate from the gate, I'm already solving for all three use cases. Example new command below for my above container. My host OS is passing through a mounted NAS into the qB container at `/downloads`, so the path to the cross-seed hardlink location should also be relative to how qB sees it, aka in this case `/downloads`, not `/mnt/nas/downloads`.

I don't know if this would necessitate an additional volume mount being available to the cross-seed container itself, but I assume not since currently that isn't required for injection, but just thought I'd raise the concern.

`command: daemon -i /torrents -s /output -e -a -A inject--qbittorrent-url http://wireguard:$WG_QB_PORT2 -ln -ld /downloads/seed/cross-seed/ -T http://prowlarr:$PROWLARR_PORT/25/api?apikey=$TRACKER1_KEY http://prowlarr:$PROWLARR_PORT/20/api?apikey=$TRACKER2_KEY http://prowlarr:$PROWLARR_PORT/19/api?apikey=$TRACKER3_KEY http://prowlarr:$PROWLARR_PORT/24/api?apikey=$TRACKER4_KEY`

--

For a really fancy use case, getting to specify the cross-seeding location per tracker would allow me to actually leverage my entire structure of `/downloads/seed/tracker1` through `/downloads/seed/tracker4` natively, thus allowing me to leverage qBittorrent's automatic torrent management file controls with not only the original torrent, but all cross-seeded matches. The prior use case would not allow that if a file exists in more than 2 trackers, because then more than 1 cross-seeded torrent would be pointing at the same data in `/downloads/seed/cross-seed/`. For this, we'll add a few more commands:

```
-ldn, --linkdirn

Specifies the folder path within qBittorrent per provided Torznab url, eg -ld1 for the first, -ld2 for the second, and so on. (One directory per Torznab URL. Requires all Torznab URLs provided to have a dedicated folder path, or requires -ld directory for fallback. Requires hard or symlinks. If -ln/-lns not specified in conjunction with -ldn, defaults to -ln. Default: false)
```

That is really a mouthful for the config and I think I could clean it up more, but a command example probably provides easier context. Here are three:

`command: daemon -i /torrents -s /output -e -a -A inject--qbittorrent-url http://wireguard:$WG_QB_PORT2 -ln -ld /downloads/seed/cross-seed/ -T http://prowlarr:$PROWLARR_PORT/25/api?apikey=$TRACKER1_KEY http://prowlarr:$PROWLARR_PORT/20/api?apikey=$TRACKER2_KEY http://prowlarr:$PROWLARR_PORT/19/api?apikey=$TRACKER3_KEY http://prowlarr:$PROWLARR_PORT/24/api?apikey=$TRACKER4_KEY -ld1 /downloads/seed/tracker1/ -ld2 /downloads/seed/tracker2/`

`command: daemon -i /torrents -s /output -e -a -A inject--qbittorrent-url http://wireguard:$WG_QB_PORT2 -ln -T http://prowlarr:$PROWLARR_PORT/25/api?apikey=$TRACKER1_KEY http://prowlarr:$PROWLARR_PORT/20/api?apikey=$TRACKER2_KEY http://prowlarr:$PROWLARR_PORT/19/api?apikey=$TRACKER3_KEY http://prowlarr:$PROWLARR_PORT/24/api?apikey=$TRACKER4_KEY -ld1 /downloads/seed/tracker1/ -ld2 /downloads/seed/tracker2/ -ld3 /downloads/seed/tracker3/ -ld4 /downloads/seed/tracker4/`

`command: daemon -i /torrents -s /output -e -a -A inject--qbittorrent-url http://wireguard:$WG_QB_PORT2 -ln -T http://prowlarr:$PROWLARR_PORT/25/api?apikey=$TRACKER1_KEY http://prowlarr:$PROWLARR_PORT/20/api?apikey=$TRACKER2_KEY http://prowlarr:$PROWLARR_PORT/19/api?apikey=$TRACKER3_KEY http://prowlarr:$PROWLARR_PORT/24/api?apikey=$TRACKER4_KEY -ld1 /downloads/seed/tracker1/  -ld2 /downloads/seed/tracker2/ -ld3 /downloads/seed/tracker3/`

In the above examples here is what I believe should happen:

1st - trackers 1 and 2's found cross-seed files should land in their respective `/downloads/seed/tracker1/` and `/downloads/seed/tracker2/` folders. Trackers 3 and 4 files' should land in `/downloads/seed/cross-seed/`
2nd - All four trackers files should land in their respective `/downloads/seed/trackerx/` folders.
3rd - This would throw an error as the user did not specify an `-ld` directory but also did not provide a `-ldn` location for each tracker (missing the 4th tracker).

Looking at it, I don't know if a numerically increasing variable flag such as `-ld1`, `-ld2`, etc. is a good solution, or if simply one that does not change but is executed in the order received would be better, such as how we're just using multiple torznab URLs against just one `-T` call. If that's the case, perhaps `-ldn` is better renamed `-tld` or `--torznablinkdir`.
