### ISSUE TITLE
5.4: Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/usr/bin/nice": stat /usr/bin/nice: no such file or directory: unknown

### ISSUE THREAD

**Issue by KyleSanderson** [cross-seed/cross-seed#457]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cross-seed
  name: cross-seed
spec:
  selector:
    matchLabels:
      app: cross-seed
  template:
    metadata:
      labels:
        app: cross-seed
    spec:
      containers:
      - command:
        - /usr/bin/nice
        - /usr/bin/ionice
        - -c3
        - -n7
        - /usr/local/bin/cross-seed
        args:
        - daemon
```
